### ISSUE TITLE
Fix chaching related issues

### ISSUE THREAD

**Issue by Luc1412** [project-cybersyn-game/project-cybersyn-game#78] opened 2022-02-22 17:09 UTC
Caching issues causing following issues in prod environment  which need to be fixed:
- [x] Overlapping of textures when standing in front of an entity

**Comment by Hutmensch** [comment] 2022-02-22 23:01
The explaination is kinda sad...
The issue wasn't caching-related but was caused by a GridEngine update we didn't download on our local machines but the server running the deploy did.
Not sure if the issue itself is caused by our code, but it runs on GridEngine version `v2.10.4`, so that one is fixed in the package.json for now.

**Closed by Hutmensch** 2022-02-22 23:01 UTC
Labels: bug
